server:
  port: 8080

spring:
  application:
    name: user
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/db1?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    service-url:
      defaultZone: http://user:password@peer1:8761/eureka/
  instance:
    prefer-ip-address: true # 当鼠标放到实例的地址时显示链接为IP地址
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}} #eureka 注册实例名称格式
    # ip-address: 192.168.109.1 #使用指定IP注册
    metadata-map:
      my-meta: my-meta
logging:
  level:
    springcloud.*: debug
